# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: docker.io/library/mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASSWORD}"

  mongo-express:
    image: docker.io/library/mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/