# Use root/example as user/password credentials
version: '3.1'

services:

  mongo_test:
    image: docker.io/library/mongo:latest
    container_name: mongo_test
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo_test:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASSWORD}"

  # mongo-express:
  #   image: docker.io/library/mongo-express:latest
  #   container_name: mongo_express_test
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  client_test:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: client_test
    environment:
      - MONGO_LOCAL_URI="mongodb://${USER}:${PASSWORD}@mongo_test:27017"
    restart: always
    # volumes:
      # - ./:/app:rw
